#	Copyright (c) 2021 Noah Stein. All Rights Reserved.

cc_library(
	name = "Ark",
	hdrs = [
		"Ark.h",
	],
	deps = [
		"//Ark/Hal:Ark-Hal",
		"//Ark/Math:Ark-Math",
	],
	visibility = ["//visibility:public"],
)
