#	Copyright (c) 2021 Noah Stein. All Rights Reserved.

cc_library(
	name = "Ark-Hal",
	srcs = [
	],
	hdrs = [
		"Hal.h",
		"Simd/SImd.h",
		"Simd/Sse.h",
		"Simd/Neon.h",
	],
	visibility = ["//visibility:public"],
)
