#	Copyright (c) 2021 Noah Stein. All Rights Reserved.

cc_library(
	name = "Ark-Hal",
	srcs = [
	],
	hdrs = [
		"Hal.h",
		"Simd/Simd.h",
		"Simd/Sse.h",
		"Simd/Sse2.h",
		"Simd/Sse3.h",
		"Simd/Sse4.h",
		"Simd/Avx.h",
		"Simd/Neon.h",
	],
	visibility = ["//visibility:public"],
)
