#	Copyright (c) 2021 Noah Stein. All Rights Reserverd.

cc_library(
	name = "Ark-Math",
	srcs = [
	],
	hdrs = [
		"Quaternion.h",
		"Quat.h",
		"Quat_SSE.h",
	],
	visibility = ["//visibility:public"],
)
