#	Copyright (c) 2021 Noah Stein. All Rights Reserved.

cc_library(
	name = "Ark-Math",
	srcs = [
	],
	hdrs = [
		"Concepts.h",
		"Matrix.h",
		"Mtx.h",
		"Quaternion.h",
		"Quat.h",
		"Quat_Sse.h",
		"Quat_Sse2.h",
		"Quat_Sse3.h",
		"Quat_Sse4.h",
		"Quat_Avx.h",
		"Quat_Avx2.h",
		"Vector.h",
		"Vec.h",
	],
	visibility = ["//visibility:public"],
)
